#!/usr/bin/env python3
"""Harness tool: compile results.json -> paper/values.tex (LaTeX macros).

This is the injection side of the no-hand-typed-numbers design: the paper may
only reference numbers through the macros generated here. Deterministic output
(sorted keys) so the diff is meaningful in git.

Formatting via each entry's optional 'fmt' (a Python format spec, e.g. '.2f',
',.0f'). Defaults: ints plain, floats '.2f'.
"""
import json
import sys
from pathlib import Path

RESULTS = Path("results.json")
OUT = Path("paper/values.tex")


def render(value, fmt):
    if fmt:
        return format(value, fmt)
    if isinstance(value, int):
        return str(value)
    return format(value, ".2f")


def main() -> int:
    if not RESULTS.exists():
        print("make_values: results.json missing — run `make results` first", file=sys.stderr)
        return 1
    data = json.loads(RESULTS.read_text())
    values = data.get("values", {})
    lines = [
        "% AUTO-GENERATED by analysis/make_values.py from results.json.",
        "% DO NOT EDIT BY HAND. Every macro here traces to an analysis script.",
    ]
    for name in sorted(values):
        entry = values[name]
        rendered = render(entry["value"], entry.get("fmt"))
        desc = entry.get("desc", "")
        lines.append(f"\\newcommand{{\\{name}}}{{{rendered}}} % {desc} [{entry.get('script','?')}]")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"make_values: wrote {len(values)} macros to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
